#!/bin/bash

echo "🚀 DEPLOYING CHANGES TO VERCEL..."

echo "📝 The changes I made:"
echo "✅ Added ultra-aggressive white background CSS"
echo "✅ Fixed dashboard card text to be black on white"
echo "✅ Made all text readable"
echo "✅ Committed changes locally"

echo ""
echo "🔧 TO COMPLETE THE DEPLOYMENT:"
echo ""
echo "Option 1 - GitHub Push (Recommended):"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Generate new token with 'repo' permissions"
echo "3. Run: git push origin main"
echo "4. Enter username: miguelstasher"
echo "5. Enter password: [paste your token]"
echo ""
echo "Option 2 - Manual Upload:"
echo "1. Zip this folder"
echo "2. Go to: https://github.com/miguelstasher/geoleads-enricher"
echo "3. Upload the zip file"
echo "4. Vercel will auto-deploy"
echo ""
echo "Option 3 - Vercel Direct:"
echo "1. Go to: https://vercel.com/oauth/device?user_code=ZSZV-HDTZ"
echo "2. Complete authentication"
echo "3. Run: vercel --prod --yes"

echo ""
echo "🎯 The changes will fix:"
echo "• Black background → White background"
echo "• Invisible text → Readable black text"
echo "• White cards → Black text on white cards"

echo ""
echo "✅ Changes are ready - just need to deploy!"
