#!/bin/bash

echo "🚀 PUSHING CHANGES TO TRIGGER VERCEL DEPLOYMENT..."
echo ""
echo "✅ Changes are committed locally:"
echo "   - f526331 ULTRA-AGGRESSIVE: Force white background everywhere"
echo "   - 9cc7aa5 Fix black background - force white theme"
echo ""
echo "🔧 TO PUSH TO GITHUB (Choose One):"
echo ""
echo "Option 1 - GitHub Token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Generate new token with 'repo' permissions"
echo "3. Run: git push https://miguelstasher@github.com/miguelstasher/geoleads-enricher.git main"
echo "4. Enter password: [paste your token]"
echo ""
echo "Option 2 - Manual Upload:"
echo "1. Go to: https://github.com/miguelstasher/geoleads-enricher"
echo "2. Click 'Upload files'"
echo "3. Upload the entire project folder"
echo "4. Commit with message: 'ULTRA-AGGRESSIVE: Force white background everywhere'"
echo ""
echo "Option 3 - Vercel Redeploy:"
echo "1. Go to: https://vercel.com/miguel-elias-projects/geoleadsenricher"
echo "2. Click 'Redeploy' on the latest deployment"
echo ""
echo "🎯 Once pushed, Vercel will automatically deploy and you'll see:"
echo "• White background instead of black"
echo "• Readable black text on white cards"
echo "• All statistics visible"
echo ""
echo "✅ The changes are ready - just need to push to GitHub!"
